config/routes.rb
Rails.application.routes.draw do


  root 'pages#home'
  get 'pages/about', to: 'pages#about'
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit,:update,:show,:destroy]

	def index
		@articles =Article.all
	end

	def new
		@article = Article.new

	end

	def create
		#render plain: params[:article].inspect
		@article =Article.new(article_params)
		if @article.save
			flash[:notice] = "Article was successfully created"
			redirect_to @article
		else
			render "new"
		end
	end

	def show
	  

	end

	def edit
	 

	end

	def update
				if @article.update(article_params)
			flash[:notice]="Article was successfully updated"
			redirect_to @article
		else
			render "edit"
		end
	end

	def destroy
	  
	  @article.destroy
	  flash[:notice]="Article was successfully deleted!"
	  redirect_to articles_path
	end

	private
	  def set_article
	  	@article =Article.find(params[:id])
	  end

	  def article_params
	  	params.require(:article).permit(:title,:description)

	  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end
  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
   <p>
   	<%= f.label :title %><br />
   	<%= f.text_field :title %>
   </p>

   <p>
    <%= f.label :description %><br />
   	<%= f.text_area :description ,rows:10 %>
   </p>
	<%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h2>Edit your articles</h2>

<%= render 'form' %>

<%= link_to "Home", articles_path %>

app/views/articles/index.html.erb
<h1>Listing all the articles</h1>
<p>
  <%= link_to "Create a new article", new_article_path %> | 
  <%= link_to "Home", root_path %>
</p>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
<% @articles.each do |a| %>
  <tr>
    <td><%= a.title %></td>
    <td><%= a.description %></td>
    <td><%= link_to "Edit", edit_article_path(a) %></td> 
    <td> <%= link_to "Show", article_path(a) %></td>
    <td> <%= link_to 'Delete', article_path(a), method: :delete, data: {confirm: 'Are you sure?'} %></td>

  </tr>
<% end %>
</table>

app/views/articles/new.html.erb
<h1>new page</h1>

<% if @article.errors.any? %>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
  	<li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render "form" %>

<%= link_to "Home", articles_path %>

app/views/articles/show.html.erb
<h2>List of data </h2>

  <p>Title: <%= @article.title %></p>
  <p>Description: <%= @article.description%></p><br />

<%= link_to "Edit", edit_article_path(@article) %> | 
<%= link_to "Home", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |name,msg| %>
  	  <ul>
  	  	<li><%= msg %></li>
  	  </ul>
  	<% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
about page

app/views/pages/home.html.erb
<h1>This is the HomePage</h1>

<%= link_to "Alpha blog", articles_path %> | <%= link_to "About", pages_about_path %>